services:
  neura:
    image: neura-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_STORAGE_DRIVER: http
        VITE_API_BASE_URL: /api
    container_name: neura
    restart: always
    env_file:
      - .env.local
    networks:
      - root_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.neura.rule=Host(`neura.institutosiqueira.com.br`)
      - traefik.http.routers.neura.entrypoints=websecure
      - traefik.http.routers.neura.tls.certresolver=mytlschallenge
      - traefik.http.services.neura.loadbalancer.server.port=3300

networks:
  root_default:
    external: true
