services:
  diagnostico:
    image: diagnostico-diagnostico:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_STORAGE_DRIVER: http
        VITE_API_BASE_URL: /api
    container_name: diagnostico
    restart: always
    env_file:
      - .env.local
    networks:
      - root_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.diagnostico.rule=Host(`diagnostico.paulinhosiqueira.com.br`)
      - traefik.http.routers.diagnostico.entrypoints=websecure
      - traefik.http.routers.diagnostico.tls.certresolver=mytlschallenge
      - traefik.http.services.diagnostico.loadbalancer.server.port=3300

networks:
  root_default:
    external: true
