/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as IndexRouteImport } from './routes/index'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dados' | '/diagnostico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dados' | '/diagnostico'
  id: '__root__' | '/' | '/dados' | '/diagnostico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DadosRoute: typeof DadosRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DadosRoute: DadosRoute,
  DiagnosticoRoute: DiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
